name: azuracast
services:
  web:
    container_name: azuracast
    image: "ghcr.io/azuracast/azuracast:latest"
    labels:
      - "com.centurylinklabs.watchtower.scope=azuracast"
    environment:
      - APPLICATION_ENV=production
      - COMPOSER_PLUGIN_MODE=false
      - AUTO_ASSIGN_PORT_MIN=8000
      - AUTO_ASSIGN_PORT_MAX=8499
      - SHOW_DETAILED_ERRORS=false
      - MYSQL_PASSWORD=azur4c457
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - '89:80'
      - '2022:2022'
      - '8000:8000'
      - '8005:8005'
      - '8006:8006'
      - '8010:8010'
      - '8015:8015'
      - '8016:8016'
      - '8020:8020'
      - '8025:8025'
      - '8026:8026'
      - '8030:8030'
      - '8035:8035'
      - '8036:8036'
      - '8040:8040'
      - '8045:8045'
      - '8046:8046'
      - '8050:8050'
      - '8055:8055'
      - '8056:8056'
      - '8060:8060'
      - '8065:8065'
      - '8066:8066'
      - '8070:8070'
      - '8075:8075'
      - '8076:8076'
      - '8090:8090'
      - '8095:8095'
      - '8096:8096'
      - '8100:8100'
      - '8105:8105'
      - '8106:8106'
      - '8110:8110'
      - '8115:8115'
      - '8116:8116'
      - '8120:8120'
      - '8125:8125'
    volumes:
      - type: bind
        source: /DATA/AppData/azuracast/stations
        target: /var/azuracast/stations
      - type: bind
        source: /DATA/AppData/azuracast/backups
        target: /var/azuracast/backups
      - type: bind
        source: /DATA/AppData/azuracast/mysql
        target: /var/lib/mysql
      - type: bind
        source: /DATA/AppData/azuracast/uploads
        target: /var/azuracast/storage/uploads
      - type: bind
        source: /DATA/AppData/azuracast/shoutcast2
        target: /var/azuracast/storage/shoutcast2
      - type: bind
        source: /DATA/AppData/azuracast/stereo_tool
        target: /var/azuracast/storage/stereo_tool
      - type: bind
        source: /DATA/AppData/azuracast/rsas
        target: /var/azuracast/storage/rsas
      - type: bind
        source: /DATA/AppData/azuracast/geoip
        target: /var/azuracast/storage/geoip
      - type: bind
        source: /DATA/AppData/azuracast/sftpgo
        target: /var/azuracast/storage/sftpgo
      - type: bind
        source: /DATA/AppData/azuracast/acme
        target: /var/azuracast/storage/acme
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    networks:
      - default
  updater:
    container_name: azuracast_updater
    image: ghcr.io/azuracast/updater:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-size: "1m"
        max-file: "5"
networks:
  default:
    name: azuracast_default
volumes:
  db_data: {}
  acme: {}
  shoutcast2_install: {}
  stereo_tool_install: {}
  rsas_install: {}
  geolite_install: {}
  sftpgo_data: {}
  station_data: {}
  www_uploads: {}
  backups: {}
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: "https://static-00.iconduck.com/assets.00/azuracast-icon-449x512-kwvh44t6.png"
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: http
  store_app_id: azuracast
  title:
    custom: "AzuraCast"
    en_us: AzuraCast
  description:
    en_us: "AzuraCast is a free and open-source self-hosted web radio management suite"
